"""add platform_commission to disputes

Revision ID: 8062778b686e
Revises: b3cc0f5d3756
Create Date: 2026-05-25 00:34:12.648197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8062778b686e'
down_revision: Union[str, Sequence[str], None] = 'b3cc0f5d3756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('platform_commission', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disputes', 'platform_commission')
    # ### end Alembic commands ###
