"""drop services.category_id

Revision ID: f6641cde9e0d
Revises: b7e2f4c91d8a
Create Date: 2026-05-05 16:32:58.367213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6641cde9e0d'
down_revision: Union[str, Sequence[str], None] = 'b7e2f4c91d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('services_category_id_fkey'), 'services', type_='foreignkey')
    op.drop_column('services', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('services_category_id_fkey'), 'services', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
